In [1]:
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline


data = pd.read_csv("origin_labeled.csv")
data.head()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>blockID</th>
      <th>txID</th>
      <th>seq</th>
      <th>addrID</th>
      <th>sum</th>
      <th>block_timestamp</th>
      <th>balance</th>
      <th>n_inputs</th>
      <th>n_outputs</th>
      <th>n_txs</th>
      <th>cluster</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td>-1.782753</td>
      <td>-1.753375</td>
      <td>-0.140317</td>
      <td>-0.514563</td>
      <td>-2.199304</td>
      <td>-1.733706</td>
      <td>0.261965</td>
      <td>-0.221446</td>
      <td>-0.107145</td>
      <td>-0.216222</td>
      <td>2</td>
    </tr>
    <tr>
      <th>2</th>
      <td>-1.782753</td>
      <td>-1.753378</td>
      <td>-0.140317</td>
      <td>-0.514563</td>
      <td>-0.598916</td>
      <td>-1.733706</td>
      <td>0.444156</td>
      <td>-0.221446</td>
      <td>-0.107145</td>
      <td>-0.216222</td>
      <td>2</td>
    </tr>
    <tr>
      <th>3</th>
      <td>-1.782753</td>
      <td>-1.753377</td>
      <td>-0.140317</td>
      <td>-0.514563</td>
      <td>-0.268953</td>
      <td>-1.733706</td>
      <td>0.424287</td>
      <td>-0.221446</td>
      <td>-0.107145</td>
      <td>-0.216222</td>
      <td>2</td>
    </tr>
    <tr>
      <th>4</th>
      <td>-1.782753</td>
      <td>-1.753378</td>
      <td>-0.140317</td>
      <td>-0.514563</td>
      <td>-2.202442</td>
      <td>-1.733706</td>
      <td>0.488375</td>
      <td>-0.221446</td>
      <td>-0.107145</td>
      <td>-0.216222</td>
      <td>2</td>
    </tr>
    <tr>
      <th>5</th>
      <td>-1.782753</td>
      <td>-1.752993</td>
      <td>-0.140317</td>
      <td>-0.911458</td>
      <td>0.000819</td>
      <td>-1.733706</td>
      <td>0.650967</td>
      <td>-0.192982</td>
      <td>-0.107145</td>
      <td>-0.216222</td>
      <td>2</td>
    </tr>
  </tbody>
</table>
</div>

In [2]:
print(data.shape)


(97816, 11)


In [3]:
print(data.groupby("cluster").size())


cluster
1    45322
2    52494
dtype: int64


In [4]:
features = list(data.columns)
print(features)

features.remove("cluster")
print(features)

['blockID', 'txID', 'seq', 'addrID', 'sum', 'block_timestamp', 'balance', 'n_inputs', 'n_outputs', 'n_txs', 'cluster']
['blockID', 'txID', 'seq', 'addrID', 'sum', 'block_timestamp', 'balance', 'n_inputs', 'n_outputs', 'n_txs']


In [5]:
x = data[features]
y = data["cluster"]




In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, 
                                                    y, 
                                                    random_state=0,
                                                    test_size=0.2)

In [7]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import numpy as np

knn = KNeighborsClassifier(2)
knn.fit(X_train, y_train)
print('Accuracy of K-NN classifier on training set: {:.5f}'.format(
    knn.score(X_train, y_train)))
print('Accuracy of K-NN classifier on test set: {:.5f}'.format(
    knn.score(X_test, y_test)))
print(confusion_matrix(y_test, knn.predict(X_test)))


Accuracy of K-NN classifier on training set: 0.99847


Accuracy of K-NN classifier on test set: 0.99647


[[ 9084    16]
 [   53 10411]]


In [8]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(X_train, y_train)
print('Accuracy of GNB classifier on training set: {:.5f}'
      .format(gnb.score(X_train, y_train)))
print('Accuracy of GNB classifier on test set: {:.5f}'
      .format(gnb.score(X_test, y_test)))
print(confusion_matrix(y_test, gnb.predict(X_test)))


Accuracy of GNB classifier on training set: 0.96320
Accuracy of GNB classifier on test set: 0.96534
[[ 8551   549]
 [  129 10335]]


In [9]:
from sklearn.svm import SVC

svm = SVC(kernel="linear", C=0.025)
svm.fit(X_train, y_train)
print('Accuracy of SVM classifier on training set: {:.5f}'
      .format(svm.score(X_train, y_train)))
print('Accuracy of SVM classifier on test set: {:.5f}'
      .format(svm.score(X_test, y_test)))
print(confusion_matrix(y_test, svm.predict(X_test)))


Accuracy of SVM classifier on training set: 0.99819


Accuracy of SVM classifier on test set: 0.99836


[[ 9085    15]
 [   17 10447]]


In [10]:
svm2 = SVC(gamma=2, C=1)
svm2.fit(X_train, y_train)
print('Accuracy of SVM classifier on training set: {:.5f}'
      .format(svm2.score(X_train, y_train)))
print('Accuracy of SVM classifier on test set: {:.5f}'
      .format(svm2.score(X_test, y_test)))
print(confusion_matrix(y_test, svm2.predict(X_test)))


Accuracy of SVM classifier on training set: 0.99839


Accuracy of SVM classifier on test set: 0.99550


[[ 9084    16]
 [   72 10392]]


In [11]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(alpha=1)
mlp.fit(X_train, y_train)
print('Accuracy of SVM classifier on training set: {:.5f}'
      .format(mlp.score(X_train, y_train)))
print('Accuracy of SVM classifier on test set: {:.5f}'
      .format(mlp.score(X_test, y_test)))
print(confusion_matrix(y_test, mlp.predict(X_test)))

Accuracy of SVM classifier on training set: 0.99687
Accuracy of SVM classifier on test set: 0.99719
[[ 9075    25]
 [   30 10434]]
